package uz.tengebank.notificationauditservice.dto;

import lombok.Getter;

import java.time.OffsetDateTime;
import java.util.UUID;

@Getter
public class EventEnvelope<T> {

    /**
     * one-time, unique identifier for the event message itself.
     * It is generated by the publishing service every single time it emits a new event.
     *
     * Idempotency: If it receives the same eventId twice
     * (due to a network retry from RabbitMQ, for example),
     * it knows to ignore the duplicate.
     */
    private UUID eventId;

    /**
     * Provided by lightweight module such as notification-audit-service-events.jar
     * It contains only POJOs for event payloads and all other services includes it.
     */
    private String eventType;

    private String version;

    private String sourceService;

    private OffsetDateTime eventTimestamp;

    private T payload;
}
